name: Build and deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      nais-manifest:
        required: true
        type: string
      nais-manifest-vars:
        required: false
        type: string
        default: ''
      project-id:
        required: true
        type: string
    secrets:
      identity-provider:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build
        uses: navikt/hag-workflows/.github/actions/build@main

  docker-image:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' || (github.event_name == 'push' && (github.ref_name == 'main' || startsWith(github.ref_name, 'dev/')))
    permissions:
      id-token: write
    outputs:
      docker-image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@v6

      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: helsearbeidsgiver
          project_id: ${{ inputs.project-id }}
          identity_provider: ${{ secrets.identity-provider }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-image
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.environment }}-gcp
          WORKLOAD_IMAGE: ${{ needs.docker-image.outputs.docker-image }}
          RESOURCE: ${{ inputs.nais-manifest }}
          VARS: ${{ inputs.nais-manifest-vars }}
